### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by ChandraOrbit** [sshh12/PwnSSHH#4]
I get an error during setup.py execution.

root@MiniPwn:~/PwnSSHH# python setup.py
  File "setup.py", line 38
    if confirm("Create/Override settings.json")
                                              ^
SyntaxError: invalid syntax

**Comment by sshh12** [comment]
When I installed Python through opkg it installed python2 by default so a lot of the scripts unfortunately weren't written to work with python3.

**Comment by sshh12** [comment]
Its likely that installing python 2 will fix the issue.
